### ISSUE TITLE
stops scraping after so many 

### ISSUE THREAD

**Issue by Janso9295** [coderpaddy/e-pet-discount-products#1]
This is the error I get 

```
Traceback (most recent call last):
  File "scrape.py", line 40, in <module>
    writer.writerow(product_dict)
  File "C:\Users\Right Click\AppData\Local\Programs\Python\Python38-32\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "C:\Users\Right Click\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2083' in position 424: character maps to <undefined>
```

**Comment by coderpaddy** [comment]
Can i ask which tag you searched?

**Comment by Janso9295** [comment]
this was the dry dog food - I tried it on another one (aquarium accessories I think it was) and it worked fine

**Comment by coderpaddy** [comment]
OK so the error should be fixed ( i didnt know github closed it lol)
re clone and let me know :D

**Comment by Janso9295** [comment]
Yep, it works thanks
